# frozen_string_literal: true

namespace :hop_setup do
  task build: :environment do
    Dir[Rails.root.join('spec/factories/**/*.rb')].each { |f| require f }
    puts 'Building hops...'
    count = 0
    # source https://en.wikipedia.org/wiki/List_of_hop_varieties #
    hop_names = ['Aalst',
                 'Admiral',
                 'Ahtanum',
                 'Amarillo',
                 'Apollo',
                 'Aramis',
                 'Azacca',
                 'Boadicea',
                 'Bor',
                 'Bramling',
                 "Brewer's Gold",
                 'Bullion',
                 'Calypso',
                 'Cascade',
                 'Centennial',
                 'Challenger',
                 'Chinook',
                 'Citra',
                 'Cluster',
                 'Coigneau',
                 'Columbus',
                 'Comet',
                 'Crystal',
                 'Ekuanot',
                 'El Dorado',
                 'Ella',
                 'Enigma',
                 'Eroica',
                 'Feux Coeur Francais',
                 'First Gold',
                 'Fuggle',
                 'Galaxy',
                 'Galena',
                 'Glacier',
                 'Goldings',
                 'Green Bullet',
                 'Greensburg',
                 'Hallertau',
                 'Hallertauer',
                 'Herald',
                 'Herkules',
                 'Hersbrucker',
                 'Horizon',
                 'Huell Melon',
                 'Iunga',
                 'Kohatu',
                 'Liberty',
                 'Lublin',
                 'Magnum',
                 'Mandarina Bavaria',
                 'Marynka',
                 'Merkur',
                 'Mosaic',
                 'Motueka',
                 'Mount Hood',
                 'Mount Rainier',
                 'Nectaron',
                 'Nelson Sauvin',
                 'Newport',
                 'Northdown',
                 'Northern Brewer',
                 'Nugget',
                 'Opal',
                 'Pacific Gem',
                 'Pacific Jade',
                 'Pacifica',
                 'Palisade',
                 'Perle',
                 'Phoenix',
                 'Pilgrim',
                 'Pilot',
                 'Pioneer',
                 'Polaris',
                 'Poperinge',
                 'Premiant',
                 'Pride of Ringwood',
                 'Progress',
                 'Rakau',
                 'Riwaka',
                 'Saaz',
                 'San Juan Ruby Red',
                 'Santiam',
                 'Saphir',
                 'Satus',
                 'Simcoe',
                 'Sladek',
                 'Smaragd',
                 'Sonnet Golding',
                 'Sorachi Ace',
                 'Southern Cross',
                 'Spalt',
                 'Spalter Select',
                 'Sterling',
                 'Sticklebract',
                 'Strisselspalt',
                 'Styrian Atlas',
                 'Styrian Aurora',
                 'Styrian Bobek',
                 'Styrian Celeia',
                 'Styrian Golding',
                 'Summer',
                 'Summit',
                 'Super Alpha',
                 'Super Pride',
                 'Sybilla',
                 'Tardif de Bourgogne',
                 'Target',
                 'Taurus',
                 'Tettnanger',
                 'Tomahawk',
                 'Tomyski',
                 'Topaz',
                 'Ultra',
                 'Vanguard',
                 'Vic Secret',
                 'Wai-iti',
                 'Waimea',
                 'Wakatu',
                 'Warrior',
                 'Whitbread Golding',
                 'Willamette',
                 'Zeus',
                 'Zythos']

    hop_names.each do |hop_name|
      count += 1 if Hop.create(name: hop_name)
    end
    puts "Created #{count} hops!"
    puts 
  end
end
