# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/hops', type: :request do
  # Hop. As you add validations to Hop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Hop.create! valid_attributes
      get hops_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      hop = Hop.create! valid_attributes
      get hop_url(hop)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_hop_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      hop = Hop.create! valid_attributes
      get edit_hop_url(hop)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Hop' do
        expect do
          post hops_url, params: { hop: valid_attributes }
        end.to change(Hop, :count).by(1)
      end

      it 'redirects to the created hop' do
        post hops_url, params: { hop: valid_attributes }
        expect(response).to redirect_to(hop_url(Hop.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Hop' do
        expect do
          post hops_url, params: { hop: invalid_attributes }
        end.to change(Hop, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hops_url, params: { hop: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested hop' do
        hop = Hop.create! valid_attributes
        patch hop_url(hop), params: { hop: new_attributes }
        hop.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the hop' do
        hop = Hop.create! valid_attributes
        patch hop_url(hop), params: { hop: new_attributes }
        hop.reload
        expect(response).to redirect_to(hop_url(hop))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hop = Hop.create! valid_attributes
        patch hop_url(hop), params: { hop: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested hop' do
      hop = Hop.create! valid_attributes
      expect do
        delete hop_url(hop)
      end.to change(Hop, :count).by(-1)
    end

    it 'redirects to the hops list' do
      hop = Hop.create! valid_attributes
      delete hop_url(hop)
      expect(response).to redirect_to(hops_url)
    end
  end
end
